# Generated by Django 5.1.6 on 2025-04-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_check_in_time_visit_check_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='host',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visitor',
        ),
    ]
