# Generated by Django 5.0.11 on 2025-04-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
