services:
  - type: web
    name: visitor-log
    env: python
    region: oregon  # Choose your preferred region
    plan: free  # Change to a paid plan for production
    buildCommand: ./build.sh
    startCommand: ./run.sh
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DATABASE_URL
        fromDatabase:
          name: visitor-log-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        sync: false  # User needs to set this
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false  # User needs to set this
      - key: EMAIL_HOST_PASSWORD
        sync: false  # User needs to set this
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: "no-reply@residencymgmt.com"
      - key: RAZORPAY_KEY_ID
        sync: false  # User needs to set this
      - key: RAZORPAY_KEY_SECRET
        sync: false  # User needs to set this
      - key: RAZORPAY_CURRENCY
        value: "INR"
      - key: RAZORPAY_COMPANY_NAME
        value: "Residency Management"

databases:
  - name: visitor-log-db
    region: oregon  # Choose your preferred region
    plan: free  # Change to a paid plan for production
    databaseName: visitor_log  # Optional
    user: visitor_log_user  # Optional 