services:
  - type: web
    name: visitor-log
    env: python
    region: oregon  # Choose your preferred region
    plan: free  # Change to a paid plan for production
    buildCommand: ./build.sh
    startCommand: gunicorn visitor_log.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: 3.11.11
      # Database URL will be automatically set when the database is created
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: DEFAULT_FROM_EMAIL
        value: "no-reply@residencymgmt.com"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_TVojXHXrNKau7G"
      - key: RAZORPAY_KEY_SECRET
        value: "DKdUCi1kFcYHLYOjjMD6uGoE"
      - key: RAZORPAY_CURRENCY
        value: "INR"
      - key: RAZORPAY_COMPANY_NAME
        value: "Residency Management"

databases:
  - name: visitor-log-db
    region: oregon
    plan: free
    ipAllowList: [] 