# Generated by Django 5.1.6 on 2025-04-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_blacklist_expiry_date_report_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
